 ARDUINO_DIR  = /usr/share/arduino
 TARGET       = claw
       ARDUINO_LIBS = Servo Wire AccelStepper SPI
#
       BOARD_TAG    = nano328
       ARDUINO_PORT = /dev/ttyUSB0
MONITOR_PORT  = /dev/ttyUSB0
MONITOR_BAUDRATE  = 57600
#
       include /usr/share/arduino/Arduino.mk
